"""empty message

Revision ID: 9ee4787ace85
Revises: e9218303855a
Create Date: 2023-01-02 22:37:49.231670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ee4787ace85'
down_revision = 'e9218303855a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(length=155),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(length=155),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.TEXT(length=155),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(),
               type_=sa.TEXT(length=155),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(),
               type_=sa.TEXT(length=155),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(),
               type_=sa.TEXT(length=155),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
