"""empty message

Revision ID: e9218303855a
Revises: 
Create Date: 2023-01-02 22:31:03.170931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9218303855a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('director', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=155),
               existing_nullable=True)

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=155),
               existing_nullable=True)

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=155),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=155),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=155),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=155),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=155),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('director', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=155),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    op.drop_table('user')
    # ### end Alembic commands ###
